### ISSUE TITLE
artUrl metadata missing

### ISSUE THREAD

**Issue by shadowking001** [badaix/snapcast#1111]
**Describe the bug**
artUrl is not sent back to Iris when playing file through Snapcast.

**Steps to Reproduce**
1. Use a docker-compose file to run Iris instances and snapserver :

```
version: "2.1"
services:

   iris-snapserver:
      container_name: iris-snapserver
      hostname: iris-snapserver
      image: jaedb/snapserver
      networks:
         - net-proxy
      ports:
         # stream
         - 1704:1704
      volumes:
         - /tmp/snapserver:/tmp
         - /opt/iris-snapserver/snapserver.conf:/etc/snapserver.conf
         - /opt/iris-snapserver/meta_mopidy.py:/usr/share/snapserver/plug-ins/meta_mopidy.py
      restart: unless-stopped
     
   iris-mopidy-jack:
      image: jaedb/iris
      container_name: iris-mopidy-jack
      hostname: iris-mopidy-jack
      networks:
         - net-proxy
      environment:
         - PIP_PACKAGES=Mopidy-Local Mopidy-YTMusic
      depends_on:
         - iris-snapserver
      volumes:
         # iris-specific storage
         - /opt/iris-mopidy-jack/data:/var/lib/mopidy/iris
         # playlists
         - /opt/iris-mopidy-jack/m3u:/var/lib/mopidy/m3u
         # config
         - /opt/iris-mopidy-jack/config/mopidy.conf:/config/mopidy.conf:ro
         # local
         - /opt/iris-mopidy-jack/local:/var/lib/mopidy/local
         # music files
         - /mnt/nas/music:/var/lib/mopidy/media:ro
         - /tmp/snapserver:/tmp
      restart: unless-stopped

   iris-mopidy-thane:
      image: jaedb/iris
      container_name: iris-mopidy-thane
      hostname: iris-mopidy-thane
      networks:
         - net-proxy
      environment:
         - PIP_PACKAGES=Mopidy-Local
      depends_on:
         - iris-snapserver
      volumes:
         # iris-specific storage
         - /opt/iris-mopidy-thane/data:/var/lib/mopidy/iris
         # playlists
         - /opt/iris-mopidy-thane/m3u:/var/lib/mopidy/m3u
         # config
         - /opt/iris-mopidy-thane/config/mopidy.conf:/config/mopidy.conf:ro
         # local
         - /opt/iris-mopidy-thane/local:/var/lib/mopidy/local
         # music files
         - /mnt/nas/music:/var/lib/mopidy/media:ro
         - /tmp/snapserver:/tmp
      restart: unless-stopped
     
networks:

   net-proxy:
      external: true
```

2. Use latest [meta_mopidy.py file](https://github.com/badaix/snapcast/blob/develop/server/etc/plug-ins/meta_mopidy.py)
3. Configure snapserver's streams for each instance :

```
source = pipe:///tmp/jack_fifo?name=JACK&controlscript=meta_mopidy.py&controlscriptparams=--mopidy-host=iris-mopidy-jack
source = pipe:///tmp/thane_fifo?name=THANE&controlscript=meta_mopidy.py&controlscriptparams=--mopidy-host=iris-mopidy-thane
```

4. Play a file through Iris interface :

![image](https://user-images.githubusercontent.com/43928955/219867693-15ef5f17-3e63-4180-bb90-fa1c40497947.png)

I can control the stream and metadata is sent back to Iris, but no thumbnail.
**(Attached) logs show that snapserver seems to fetch thumbnail from Mopidy-Local thumbnail database.**
I tried to wget the same image from inside the container, and the download is functional.

**Environment details**
- OS: **Docker**
- Snapcast version **0.27.0**
- Installed from a package, self compiled, ... : **[jaedb's image](https://hub.docker.com/r/jaedb/snapserver)**

**Attach logfile if applicable**

```
2023-02-18 12-25-52.266 [Info] (PcmStream) Stream: JACK, message: 2023-02-18 12:25:52,266 meta_mopidy INFO: New properties: {'playbackStatus': 'playing', 'shuffle': False, 'volume': 60, 'mute': False, 'position': 0.277, 'loopStatus': 'none', 'canGoNext': True, 'canGoPrevious': True, 'canPlay': True, 'canPause': True, 'canSeek': True, 'canControl': True, 'metadata': {'url': 'local:track:bibliotheque/albums%20et%20various/Puggy%20-%20Dubois%20died%20today/01%20-%20Dubois.flac', 'title': 'Dubois', 'musicbrainzArtistId': '5049ba10-e082-480b-b5da-0b89a1869e84', 'artist': ['Puggy'], 'genre': ['Indie'], 'trackNumber': 1, 'trackId': '1', 'discNumber': 1, 'contentCreated': '2007', 'duration': 212.693, 'musicbrainzTrackId': 'fe0d5d53-3d7c-49ee-a6d2-ffc161bcbd46'}}
2023-02-18 12-25-52.277 [Info] (PcmStream) Stream: JACK, message: 2023-02-18 12:25:52,277 meta_mopidy INFO: New properties: {'playbackStatus': 'playing', 'shuffle': False, 'volume': 60, 'mute': False, 'position': 0.277, 'loopStatus': 'none', 'canGoNext': True, 'canGoPrevious': True, 'canPlay': True, 'canPause': True, 'canSeek': True, 'canControl': True, 'metadata': {'url': 'local:track:bibliotheque/albums%20et%20various/Puggy%20-%20Dubois%20died%20today/01%20-%20Dubois.flac', 'title': 'Dubois', 'musicbrainzArtistId': '5049ba10-e082-480b-b5da-0b89a1869e84', 'artist': ['Puggy'], 'genre': ['Indie'], 'trackNumber': 1, 'trackId': '1', 'discNumber': 1, 'contentCreated': '2007', 'duration': 212.693, 'musicbrainzTrackId': 'fe0d5d53-3d7c-49ee-a6d2-ffc161bcbd46', 'artUrl': 'http://iris-mopidy-jack:6680/local/5e305d8a01a28b7ce1213054c3410da0-640x640.jpeg'}}
```
